/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3f8092d1-6506-4a81-8104-e2484d24d882",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PN2wSfCaF",
    "aws_user_pools_web_client_id": "6anj7v4e1v34butjfrq2m1df06",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "tongues16254ff6006a42ae85aaa8cf09ad174e190339-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
